name: Pushing Docker Image to ECR
jobs:
  ECR-push:
    name: Build Docker Image
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout
        uses: actions/checkout@v2    
          
      - name: Setup AWS IAM
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
 
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: lravel_repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd $GITHUB_WORKSPACE  # Change directory to the root of the repository
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
